Add missing stuff. Still has build error
Build error-
/var/lib/jenkins/jobs/aosx/workspace/kernel/sony/u8500/arch/arm/mach-ux500/board-rio-grande-mcde.c:584:3: error: implicit declaration of function 'cpu_is_u8500' [-Werror=implicit-function-declaration]